// Supabase Database types
// This file will be auto-generated by Supabase CLI
// For now, we'll use a simplified version

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      leads: {
        Row: {
          id: string
          phone: string
          name: string | null
          status: string
          source: string
          interest: string | null
          assigned_to: string | null
          tags: string[]
          metadata: Json
          created_at: string
          updated_at: string
          last_contact_at: string | null
        }
        Insert: {
          id?: string
          phone: string
          name?: string | null
          status?: string
          source?: string
          interest?: string | null
          assigned_to?: string | null
          tags?: string[]
          metadata?: Json
          created_at?: string
          updated_at?: string
          last_contact_at?: string | null
        }
        Update: {
          id?: string
          phone?: string
          name?: string | null
          status?: string
          source?: string
          interest?: string | null
          assigned_to?: string | null
          tags?: string[]
          metadata?: Json
          created_at?: string
          updated_at?: string
          last_contact_at?: string | null
        }
      }
    }
  }
}
